apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: iot-sensor-build
  namespace: iot-quarkus
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - default: package
      name: GOALS
      type: string
    - default: gcr.io/cloud-builders/mvn
      name: MAVEN_IMAGE
      type: string
    - default: .
      name: CONTEXT_DIR
      type: string
    - default: iot-sensor-simulator
      name: BUILD_APP_IMAGE
      type: string
    - default: .
      name: BUILD_CONTEXT
      type: string
    - default: Dockerfile
      name: BUILD_DOCKERFILE_PATH
      type: string
    - default: 'false'
      name: BUILD_TLSVERIFY
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: build-workspace
    - name: mvn-build
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: build-workspace
        - name: maven-settings
          workspace: build-workspace
    - name: build-and-push-image
      params:
        - name: IMAGE
          value: $(params.BUILD_APP_IMAGE)
        - name: DOCKERFILE
          value: $(params.BUILD_DOCKERFILE_PATH)
        - name: TLSVERIFY
          value: $(params.BUILD_TLSVERIFY)
        - name: CONTEXT
          value: $(params.BUILD_CONTEXT)
      runAfter:
        - mvn-build
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: build-workspace
  workspaces:
    - name: build-workspace
